export const UI = {
  LOGIN_BTN: 'Entrar',
  LOGIN_BTN_REGISTER: 'Registrarse',
  LOGIN_TOGGLE_HAS_ACCOUNT: 'Ya tengo cuenta',
  LOGIN_TOGGLE_REGISTER: '¿No tienes cuenta? Regístrate',
  LOGIN_ERROR_DEFAULT: 'Credenciales incorrectas',
  LOGIN_ERROR_REQUIRED: 'Email y contraseña son obligatorios',
  LOGIN_ERROR_NAME_REQUIRED: 'El nombre es obligatorio para registrarse.',
  LOGIN_ERROR_GENERIC: 'Error al iniciar sesión.',
  LOGIN_ERROR_NETWORK: 'Error de red. Intenta de nuevo.',

  LOGOUT_TITLE: '¿Cerrar sesión?',
  LOGOUT_MSG: 'Se cerrará tu sesión actual.',
  LOGOUT_BTN: 'Cerrar sesión',

  TRANSCRIPTION_ERROR_PREFIX: 'Error de transcripción: ',
  RECORDING_AUTO_STOP: 'Grabación detenida automáticamente (5 min)',
  MIC_DENIED: 'Permiso de micrófono denegado. Activa el micrófono en la barra de direcciones.',
  MIC_NOT_FOUND: 'No se encontró ningún micrófono conectado.',
  MIC_RECORDER_ERROR: 'Error en MediaRecorder',

  LOAD_MORE: 'Cargar más',
  CLEAR_ALL_TITLE: '¿Borrar todas las incidencias?',
  CLEAR_ALL_MSG: 'Esta acción no se puede deshacer.',

  TYPE_AUDIO: 'Audio',
  TYPE_TEXT: 'Texto',
  STATUS_PROCESSING: 'Procesando',
  STATUS_COMPLETED: 'Completado',
  STATUS_ERROR: 'Error',
  STATUS_SENT: 'Enviado',
  DELETE_LABEL: 'Eliminar',
  NO_BUG_MSG: 'No hay información suficiente para generar el ticket.',
  NO_VOICE: 'No se detecto voz. Intenta grabar de nuevo.',
  RETRY_BTN: 'Reintentar',
  SUMMARIZE_ERROR_PREFIX: 'Error al resumir: ',

  TICKET_BTN: 'Crear ticket',
  TICKET_CREATE_BTN: 'Crear ticket en ClickUp',
  TICKET_VIEW: 'Ver ticket',
  TICKET_VIEW_CLICKUP: 'Ver en ClickUp',
  TICKET_TITLE_REQUIRED: 'El título es obligatorio.',
  TICKET_NO_MEMBER: 'Error: Comunícate con el gestor de ClickUp en Alfred Smart.',
  TICKET_ATTACHMENTS_PARTIAL: 'Ticket creado pero algunos adjuntos fallaron.',
  TICKET_ATTACHMENTS_RETRY: 'Reintentar adjuntos',
  TICKET_ATTACHMENTS_OK: 'Adjuntos subidos correctamente.',
  TICKET_ATTACHMENTS_FAIL: 'Los adjuntos siguen fallando. Intenta de nuevo.',
  TICKET_CREATED: 'Ticket creado.',
  TICKET_CAMERA_DENIED: 'Cámara sin permisos.',
  TICKET_PHOTO_ERROR: 'Error al capturar la foto.',
  TICKET_MISSING_APP: 'Producto',
  TICKET_MISSING_PLATFORM: 'Plataforma',
  TICKET_MISSING_APP_VERSION: 'Versión',
  TICKET_MISSING_ASSET_ID: 'ID de Asset o Proyecto',

  ATTACH_TYPE_NOT_ALLOWED: (name) => `Tipo de archivo no permitido: ${name}. Solo imágenes y vídeos.`,
  ATTACH_TOO_LARGE: (name) => `${name} excede el límite de 50 MB.`,
  ATTACH_MAX_FILES: (max, current) => `Máximo ${max} archivos. Ya tienes ${current}.`,

  CONFIRM_DELETE: 'Borrar',

  CLIPBOARD_DENIED: 'No se pudo leer el portapapeles. Pega el texto manualmente.',
  CLIPBOARD_EMPTY: 'El portapapeles esta vacio.',
};

export const API_ERRORS = {
  RATE_LIMITED: 'Demasiados intentos. Espera un minuto.',
  INVALID_NAME: 'Nombre inválido (1-100 caracteres)',
  INVALID_EMAIL: 'Email inválido',
  WEAK_PASSWORD: 'Contraseña: mínimo 6 caracteres',
  EMAIL_DOMAIN: 'Email debe ser del dominio permitido',
  EMAIL_TAKEN: 'Email ya registrado',
  INVALID_CREDENTIALS: 'Credenciales incorrectas',
  REQUIRED_FIELDS: 'Email y contraseña son obligatorios',
  UNAUTHORIZED: 'No autorizado',
  INVALID_ID: 'ID inválido',
  NOT_FOUND: 'Incidencia no encontrada',
  NO_VALID_FIELDS: 'No hay campos válidos para actualizar',
  TRANSCRIPT_REQUIRED: 'Transcript es obligatorio',
  NAME_REQUIRED: 'Nombre es obligatorio',
  CLICKUP_NOT_CONFIGURED: 'ClickUp no está configurado en el servidor',
  NO_MEMBER: 'No eres miembro del workspace de ClickUp',
  TASK_ID_REQUIRED: 'Task ID es obligatorio',
  FILE_REQUIRED: 'Se requiere al menos un archivo',
  API_KEY_MISSING: 'API key no configurada',
  EMPTY_RESPONSE: 'Respuesta vacía del servidor',
  INVALID_JSON: 'Respuesta inválida del servidor',
  TIMEOUT: 'El servidor tardó demasiado en responder',
  CLICKUP_API_ERROR: 'Error al comunicarse con ClickUp',
  UPLOAD_ERROR: 'Error subiendo archivo',
  INTERNAL_ERROR: 'Error interno',
  UNKNOWN: 'Ha ocurrido un error',
};

export function apiError(code) {
  return API_ERRORS[code] || API_ERRORS.UNKNOWN;
}
